// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwhhwwdefywzfnojowja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3aGh3d2RlZnl3emZub2pvd2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjcxMzYsImV4cCI6MjA2MTAwMzEzNn0.xt5nA6AeS1eZ1LCqFgaV-S3qh-Y7Me8IU6rwLYdYMGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);